### ISSUE TITLE
Crash with Catalogue

### ISSUE THREAD

**Issue by EdwardTheMememan** [axperty/moredelight-forge#8]
Scrolling down to the mod using the Catalogue mod menu (https://www.curseforge.com/minecraft/mc-mods/catalogue) on 1.21.1 crashes the game:

at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.render(CatalogueModListScreen.java:198) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23499!/:?] {re:classloading}
at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:112) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin from mod fabric_screen_api_v1,pl:mixin:APP:balm.neoforge.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenAccessor from mod fabric_screen_api_v1,pl:mixin:APP:polytone-common.mixins.json:ScreenMixin from mod polytone,pl:mixin:APP:emi.mixins.json:ScreenMixin from mod emi,pl:mixin:APP:konkrete.mixins.json:client.IMixinScreen from mod konkrete,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen from mod patchouli,pl:mixin:APP:rocknroller.mixins.json:MixinScreen from mod rocknroller,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin from mod ae2,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/neoforge@21.1.42/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:428) ~[neoforge-21.1.42-universal.jar%23454!/:?] {re:mixin,re:classloading,pl:mixin:A}
at TRANSFORMER/neoforge@21.1.42/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:422) ~[neoforge-21.1.42-universal.jar%23454!/:?] {re:mixin,re:classloading,pl:mixin:A}
at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$drawScreen$252(GameRenderer.java) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:polytone-common.mixins.json:GameRendererMixin from mod polytone,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod sodium_extra,pl:mixin:APP:mixins.iris.json:GameRendererAccessor from mod iris,pl:mixin:APP:mixins.iris.json:MixinGameRenderer from mod iris,pl:mixin:APP:mixins.iris.json:MixinModelViewBobbing from mod iris,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin from mod dynamic_fps,pl:mixin:APP:aoa3.mixins.json:client.function.GameRendererMixin from mod aoa3,pl:mixin:APP:aoa3.mixins.json:client.patch.GameRendererMixin from mod aoa3,pl:mixin:APP:tslateffectslib.mixins.json:client.GameRendererMixin from mod tslateffectslib,pl:mixin:APP:sodium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod sodium,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:konkrete.neoforge.mixins.json:client.MixinGameRenderer from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:mixins.artifacts.common.json:ability.nightvision.client.GameRendererMixin from mod artifacts,pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer from mod justzoom,pl:mixin:APP:betterf1.mixins.json:GameRendererMixin from mod betterf1,pl:mixin:APP:mixins.iris.json:MixinGameRenderer_NightVisionCompat from mod iris,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod securitycraft,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.wrapOperation$dcj000$konkrete$wrapRenderScreen_Konkrete(GameRenderer.java:7281) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:polytone-common.mixins.json:GameRendererMixin from mod polytone,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod sodium_extra,pl:mixin:APP:mixins.iris.json:GameRendererAccessor from mod iris,pl:mixin:APP:mixins.iris.json:MixinGameRenderer from mod iris,pl:mixin:APP:mixins.iris.json:MixinModelViewBobbing from mod iris,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin from mod dynamic_fps,pl:mixin:APP:aoa3.mixins.json:client.function.GameRendererMixin from mod aoa3,pl:mixin:APP:aoa3.mixins.json:client.patch.GameRendererMixin from mod aoa3,pl:mixin:APP:tslateffectslib.mixins.json:client.GameRendererMixin from mod tslateffectslib,pl:mixin:APP:sodium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod sodium,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:konkrete.neoforge.mixins.json:client.MixinGameRenderer from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:mixins.artifacts.common.json:ability.nightvision.client.GameRendererMixin from mod artifacts,pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer from mod justzoom,pl:mixin:APP:betterf1.mixins.json:GameRendererMixin from mod betterf1,pl:mixin:APP:mixins.iris.json:MixinGameRenderer_NightVisionCompat from mod iris,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod securitycraft,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1092) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:polytone-common.mixins.json:GameRendererMixin from mod polytone,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod sodium_extra,pl:mixin:APP:mixins.iris.json:GameRendererAccessor from mod iris,pl:mixin:APP:mixins.iris.json:MixinGameRenderer from mod iris,pl:mixin:APP:mixins.iris.json:MixinModelViewBobbing from mod iris,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin from mod dynamic_fps,pl:mixin:APP:aoa3.mixins.json:client.function.GameRendererMixin from mod aoa3,pl:mixin:APP:aoa3.mixins.json:client.patch.GameRendererMixin from mod aoa3,pl:mixin:APP:tslateffectslib.mixins.json:client.GameRendererMixin from mod tslateffectslib,pl:mixin:APP:sodium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod sodium,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:konkrete.neoforge.mixins.json:client.MixinGameRenderer from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:mixins.artifacts.common.json:ability.nightvision.client.GameRendererMixin from mod artifacts,pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer from mod justzoom,pl:mixin:APP:betterf1.mixins.json:GameRendererMixin from mod betterf1,pl:mixin:APP:mixins.iris.json:MixinGameRenderer_NightVisionCompat from mod iris,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod securitycraft,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1195) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:sodium-extra.mixins.json:core.MixinMinecraftClient from mod sodium_extra,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod sodium_extra,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Images from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Keybinds from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_PipelineManagement from mod iris,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient from mod mafglib,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin from mod dynamic_fps,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod the_bumblezone,pl:mixin:APP:puffish_skills.mixins.json:MinecraftClientMixin from mod puffish_skills,pl:mixin:APP:aoa3.mixins.json:client.function.MinecraftMixin from mod aoa3,pl:mixin:APP:sodium.mixins.json:core.MinecraftMixin from mod sodium,pl:mixin:APP:polytone-common.mixins.json:MinecraftMixin from mod polytone,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft from mod glitchcore,pl:mixin:APP:mixins.sodiumdynamiclights.json:MinecraftClientMixin from mod sodiumdynamiclights,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadEnd from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:monolib.mixins.json:MixinMinecraft from mod monolib,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:configuration.mixins.json:MinecraftMixin from mod configuration,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:irons_spellbooks.mixins.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin from mod securitycraft,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:sodium-extra.mixins.json:core.MixinMinecraftClient from mod sodium_extra,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod sodium_extra,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Images from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_Keybinds from mod iris,pl:mixin:APP:mixins.iris.json:MixinMinecraft_PipelineManagement from mod iris,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient from mod mafglib,pl:mixin:APP:dynamic_fps-common.mixins.json:MinecraftMixin from mod dynamic_fps,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod the_bumblezone,pl:mixin:APP:puffish_skills.mixins.json:MinecraftClientMixin from mod puffish_skills,pl:mixin:APP:aoa3.mixins.json:client.function.MinecraftMixin from mod aoa3,pl:mixin:APP:sodium.mixins.json:core.MinecraftMixin from mod sodium,pl:mixin:APP:polytone-common.mixins.json:MinecraftMixin from mod polytone,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft from mod glitchcore,pl:mixin:APP:mixins.sodiumdynamiclights.json:MinecraftClientMixin from mod sodiumdynamiclights,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadEnd from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:monolib.mixins.json:MixinMinecraft from mod monolib,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:configuration.mixins.json:MinecraftMixin from mod configuration,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:irons_spellbooks.mixins.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin from mod securitycraft,pl:mixin:A,pl:runtimedistcleaner:A}
at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:classloading,pl:runtimedistcleaner:A}
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.24.jar%23137!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.24.jar%23137!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.24.jar%23137!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.24.jar%23137!/:4.0] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23174!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23174!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23174!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23174!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23174!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23174!/:?] {}
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23174!/:?] {}
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
Caused by: java.io.IOException: Bad PNG Signature
at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.PngInfo.validateHeader(PngInfo.java:44) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:classloading}
at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.NativeImage.read(NativeImage.java:139) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.textures.NativeImageAccessor from mod sodium,pl:mixin:A}
at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.NativeImage.read(NativeImage.java:111) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.textures.NativeImageAccessor from mod sodium,pl:mixin:A}
at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.NativeImage.read(NativeImage.java:102) ~[client-1.21.1-20240808.144430-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.textures.NativeImageAccessor from mod sodium,pl:mixin:A}
at TRANSFORMER/catalogue@1.10.2/com.mrcrayfish.catalogue.platform.NeoForgePlatformHelper.loadNativeImage(NeoForgePlatformHelper.java:58) ~[catalogue-neoforge-1.21.1-1.10.2.jar%23499!/:?] {re:classloading}
... 35 more

**Comment by axperty** [comment]
Hi Edward,

This issue might be caused by Sodium and Catalogue, seems like there might be a compatibility issue, the log you provided has no mention of the Crate Delight mod.

Have a good day,
Axperty.
